import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Footer from '../components/Footer'
import ResponsiveAppBar from '../components/ResponsiveAppBar'
const logoBlack = require('../assets/BBBlack.png');

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>BhattiBytes Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ResponsiveAppBar />
      <main className={styles.main}>

        <Image src={logoBlack.default.src} alt="BhattiBytes Logo" height="750px" width="750px"/>

      </main>
      <Footer/>
    </div>
  )
}
